### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by xibosun** [cqels/LSBench#2]
Hi, sorry to border you!
This repo is fantastic and I would like to create some streaming graph data.
However, when I run the runExp.sh file, an error occurs as shown below.
```
$ ./runExp.sh 
Home directory of the generator is /home/xibo/Documents/repos/LSBench/main
java -Xmx16000M -XX:-UseGCOverheadLimit sib.generator.ScalableGenerator 1 /home/xibo/Documents/repos/LSBench/main/outputDir/ /home/xibo/Documents/repos/LSBench/main/ -v -stream
Map Reduce File Idx is: 0
Current directory in ScaleGenerator is /home/xibo/Documents/repos/LSBench/main/
Heap size at tihe beginning 
Generate Post and Photo Stream 
Building locations dictionary 
Done ... 118 locations were extracted
Sorted location according to their z-value 
Building interests dictionary & locations/interests distribution 
Done ... 35 interests were extracted 
Building dictionary of articles 
30 stop words extracted 
Extracting regional articles 
Done ... 5036 location-related articles have been extracted 
Extracting interest-related articles 
Done ... 379 interest-related articles have been extracted 
Extract surnames/givenNames by locations ...
Done ... 99688 names were extracted 
Done ... 465 email domains were extracted
Done ... 5 browsers were extracted
Building dictionary of organizations (by locations)
Done ... 8804 organizations were extracted
Get list of top institutes ...
Done ... 297 top universities were extracted
Building dictionary of companies (by locations)
Done ... 1593 companies were extracted
Building dictionary of popular places (by countries)
Done ... 55805 popular places were extracted
Building user agents dictionary
Done ... 9 agents have been extracted 
Number of files 1
Number of cells per file 10
Number of cells in last file 10
Dictionary building  takes 0 minutes and 8 seconds

New storage manager: 0_mr0_userProf.ser
New storage manager: 1_mr0_userProf.ser
New storage manager: 2_mr0_userProf.ser
Heap size before generating friendships at pass 0
Pass 0 Total 3525 friendships generated
Heap size after generating friendships at pass 0
Friendship generation in pass 0 takes 0 minutes and 0 seconds
Heap size before sorting 1
Size of file is 593268
End of file --- 
Exception in thread "Thread-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:777)
	at java.util.TimSort.mergeAt(TimSort.java:514)
	at java.util.TimSort.mergeCollapse(TimSort.java:439)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:177)
	at sib.util.ExternalSort.sortAndSave(ExternalSort.java:163)
	at sib.util.ExternalSort.sortInBatch(ExternalSort.java:140)
	at sib.util.ExternalSort.SortByDimensions(ExternalSort.java:280)
	at sib.generator.ScalableGenerator.sortByDimensions(ScalableGenerator.java:1199)
	at sib.generator.ScalableGenerator.prepareMRInput(ScalableGenerator.java:463)
	at sib.generator.ScalableGenerator.run(ScalableGenerator.java:408)
	at java.lang.Thread.run(Thread.java:748)
```
What can I do to solve it? My java version is 1.8.0_242.
Thank you very much!

**Comment by xibosun** [comment]
I downgrade java to 1.6.0 and it's solved. Thanks!
